### ISSUE TITLE
Cannot require electron-json-storage

### ISSUE THREAD

**Issue by heaversm** [jviotti/electron-json-storage#24] opened 2016-09-12 22:31 UTC
I have an electron app - in the renderer, I set a bunch of configuration variables, like:

```
Constants = namespace.Constants = {
    SHADOWS: false, //render shadows?
}
```

Then, as the system starts up, it reads the value of those variables and configures the application environment. 

Now, in my main process, I build I tray menu:

```
    function createTray (){
      mainWindow.toggleDevTools();
      tray = new Tray(iconPath);
      contextMenu = Menu.buildFromTemplate([
        {label: 'Shadows', type: 'checkbox', checked: false, click: function(item){
          contextMenu.items[0].checked = contextMenu.items[0].checked;
          tray.setContextMenu(contextMenu);
          mainWindow.webContents.send('toggleShadows', contextMenu.items[0].checked);
        }},
      ])
      tray.setToolTip('Jordan')
      tray.setContextMenu(contextMenu)
    }
```

I then hooked up the ipc renderer to be able to detect that change in the context menu:

```
    const {ipcRenderer} = require('electron');

    ipcRenderer.on('toggleShadows', (event, message) => {
      Constants.SHADOWS = message;
    });
```

This works to change the value of that variable, the problem is, the variable is only taken into consideration when Constants is initialized, so toggling from the tray after initialization has no effect. So I decided to utilize electron json storage. Then I run:

```
npm install --save electron-json-storage
```

Then I require it in my main process:

```
const {storage} = require('electron-json-storage');
```

And then modified my contextMenu click listener:

```
contextMenu = Menu.buildFromTemplate([
    {label: 'Shadows', type: 'checkbox', checked: storage.get('shadows'), click: function(item){
      tray.setContextMenu(contextMenu);
      //mainWindow.webContents.send('toggleShadows', contextMenu.items[0].checked);
      storage.set('shadows', contextMenu.items[0].checked, function(error) {
          if (error) throw error;
      });
  mainWindow.webContents.reload();

}},
```

so that it tries to retrieve the currently set value from storage, then reloads the browser.

And in the renderer, I set it up to retrieve the set value as well:

```
Constants = namespace.Constants = {
    SHADOWS: storage.get('shadows'),
}
```

I can see the tray icon setting being toggled on and off, and the browser reloads, but no change is being registered to the shadows. 

How do I make these changes from the tray icon persist?

**Comment by jviotti** [comment] 2016-09-14 15:19
Hi @heaversm ,

Thanks for reaching out. I believe the issue is in the following snippet:

```
Constants = namespace.Constants = {
    SHADOWS: storage.get('shadows'),
}
```

Notice that `.get()` is an asynchronous function, and you have to pass it a callback to be able to retrieve the actual `shadows` value, so it should look something like this instead:

```
storage.get('shadows', function(error, shadowsValue) {
  Constants = namespace.Constants = {
      SHADOWS: shadowsValue,
  }
});
```

Let me know if that fixes your issue! If it doesn't, it'd be great if you can link me to the source code somewhere, or build a quick example I could run myself and be able to help further!

**Comment by jviotti** [comment] 2016-11-12 10:12
I'm closing this as resolved. Please re-open if you have any other issues!

**Closed by jviotti** 2016-11-12 10:12 UTC
