### ISSUE TITLE
Cannot find module 'bluebird'

### ISSUE THREAD

**Issue by ColeTownsend** [jviotti/electron-json-storage#2] opened 2016-02-06 01:58 UTC
Digging into my Resources in the app, the dependencies are installed, but this app can't find them. I'm using it with `remote`, wondering if that has anything to do with it. It seems however to be an issue with bluebird.

<img width="912" alt="screenshot 2016-02-05 20 57 09" src="https://cloud.githubusercontent.com/assets/987654/12863864/23b58d18-cc4b-11e5-847f-34005faaaecb.png">

I tried manually including all of the dependencies:

<img width="559" alt="screenshot 2016-02-05 20 57 22" src="https://cloud.githubusercontent.com/assets/987654/12863866/2d786744-cc4b-11e5-85cf-ff0bc962df08.png">

**Comment by jviotti** [comment] 2016-02-07 02:29
@ColeTownsend That's very weird. Can you try if it works by loading it without `remote`? I'll be on mobile the rest of the weekend, but will try to reproduce myself on Monday.

**Comment by jviotti** [comment] 2016-02-07 02:32
@ColeTownsend I managed to borrow a laptop but couldn't reproduce the error. Could it be that somehow `node_modules/bluebird` got corrupted somehow (maybe bad internet connection)? Can you wipe out `node_modules` and try `npm install` from scratch?

Also, are you packaging your app in some way that could trigger the error, like in an `asar` package?

**Comment by ColeTownsend** [comment] 2016-02-07 02:37
I tried wiping node modules a few times, resetting the npm cache and reinstalling. I use the electron packager without asar and still couldn't find it. I also tried manually installing all the dependencies and it still wouldn't import. 

It's seems like there may be a problem with Babel not liking promises.

Have you built and packaged an app with this?

**Comment by jviotti** [comment] 2016-02-07 02:56
@ColeTownsend I work on an app that makes use of this module without any issue (I'm not allowed to share the source code, sorry), however we don't use Babel. Is the application you're working on open-source? Can I try myself somehow? Some other thoughts:

- What Electron version are you running? I've been running this module with v0.36.2.
- You can try exposing `NODE_DEBUG=module`, which should give your more debug information about how the module is being looked, etc.
- Can you confirm `bluebird` is installed under your project's `node_modules/` and/or `electron-json-storage/node_modules/`?

**Comment by jviotti** [comment] 2016-02-07 02:58
In case you're not allowed to share your app, can you try building a minimal project that reproduces the issue for you?

**Comment by jviotti** [comment] 2016-03-13 18:42
v2.0.0 removes promise support (and thus Bluebird), so the issue should be fixed there.

**Closed by jviotti** 2016-03-13 18:42 UTC

**Comment by ColeTownsend** [comment] 2016-03-13 20:44
@jviotti woo! very exciting news. I'll let you know how it goes.

**Comment by jviotti** [comment] 2016-03-13 22:16
@ColeTownsend Actually, I published this change 16 days ago, but completely forgot to announce it in this issue. Sorry about that!

**Comment by benjick** [comment] 2016-08-01 10:59
Will you bring promises back?

**Comment by jviotti** [comment] 2016-08-01 13:50
Hi @benjick ,

I don't think so, at least for now, but promisifying the module should be trivial:

```js
const Promise = require('bluebird').
const storage = Promise.promisifyAll(require('electron-json-storage'));
```

You can then use the functions suffixed with `Async`:


```js
storage.getAsync('foobar').then(function(data) {
  console.log(data);
});
```

See [Bluebird's documentation](http://bluebirdjs.com/docs/api/promise.promisifyall.html) for a more detailed explanation.

**Comment by benjick** [comment] 2016-08-01 14:09
Thank you 👍
